### ISSUE TITLE
Mixing positional, and named params causes optional to not work in named parameter

### ISSUE THREAD

**Issue by cazador481** [houseabsolute/Params-CheckCompiler#12]
Ex:
```
package Ea;
sub test_ea {
    my $check=validation_for(params=>[ {type=> InstanceOf[__PACKAGE__]}, ea=>{type=>Int,default=>1,optional=>1} ]);
    my ($self,%args)=$check->(@_);
    print Dumper \%args;
}
sub run {
my $self=shift
$self->test_ea();
}
__PACKAGE__->run;
```

This returns:
got 1 parameter but expected at least 2
shell returned 255

**Comment by autarch** [comment]
There is no support for mixing named and positional params. In the _general_ case, I'm not even sure how it could work at all. Perl doesn't let us distinguish between the two if you pass them all as a list like `foo( 42, foo => 84 )`. I don't think trying to add this would be worth the effort.

In the _specific_ case of "this is a method", that could be supported easily enough. I think a new `method => 1` parameter could be passed to the `validation_for` sub which would cause it to simple shift off the first argument and return that separately. A PR for this would be welcome.

BTW, this may just be example code you pasted, but just in case it's not ... calling `validation_for` on every subroutine call completely defeats the purpose of this module. You're recompiling your parameter checker on every method call. What you want to do is something like this:

```perl
{
    my $check = validation_for(...);
    sub foo {
        my %args = $check->(@_);
        ...
    }
}
```

**Comment by cazador481** [comment]
As an FYI, I did test the case of not using optional named params.  And the code seemed to be able handle the mixed case.

**Comment by autarch** [comment]
Inasmuch as it worked that was an accident. It definitely is not designed to handle a mix of positional and named params. What is happening is that it's treating this spec as requesting validation of _three_ positional params, with the last being optional.

**Comment by autarch** [comment]
I'm going to close this because this isn't really a bug, and there's no way to change how this works.
