### ISSUE TITLE
Type::Tiny warnings

### ISSUE THREAD

**Issue by xenu** [houseabsolute/Params-CheckCompiler#14]
Following code produces `Found = in conditional, should be == at (eval 79) line 55.` warning:

```perl
use Types::Standard qw( Dict Int );
use Params::ValidationCompiler qw( validation_for );

my $validator = validation_for(
    params => {
        foo => { type => Dict[name => Int] },
    }
);
```

Not sure what's the right way to fix it. I feel that it should be fixed in `Type::Tiny`, but TOBYINK doesn't seem to agree (see [this issue](https://github.com/tobyink/p5-type-tiny/issues/24)). 

Maybe `Params::ValidationCompiler` should add `no warnings` to inlined type checks/coercions?

**Comment by autarch** [comment]
I'm a bit wary of disabling warnings since people could be creating typed with inclining where the warnings world reveal real issues. It really seems like TT should lexically disable warnings in the code it generates if it knows it might warn.

**Comment by xenu** [comment]
Oohh, sorry, looks like it **[is](https://github.com/tobyink/p5-type-tiny/commit/249efe3bc8407ca7c6c0fc864ec437531ed08076)** fixed in the latest dev release of `Type::Tiny`. The fix didn't make it to the stable branch yet :)

Closing.
