### ISSUE TITLE
Add on_fail callback

### ISSUE THREAD

**Issue by dwright** [houseabsolute/Params-CheckCompiler#17]
This is a request to implement an on_fail callback, similar to the one in Params::Validate.    The idea being that I want to be able to throw my own error class when an exception happens.

Note, it's pretty easy to work around that issue right now with something like the following, however it would be nice if this came built-in:

```perl
sub _build_validator {
    my $validator = validation_for( @_ );
    return sub {
        my @return = eval { $validator->(@_) };
        if ( $@ ) { die My::Error::Class->new($@) }
        return $@;
    };
}
```

**Comment by autarch** [comment]
So right now P::VC throws several different exception classes. All of these classes have a `message`, but some of them also take other constructor arguments like a parameter name or the number of parameters passed.

What would the exact API be for an `on_fail` callback? Should it take a list of k/v pairs where one of the pairs is always going to be a `message` key?

**Comment by dwright** [comment]
After playing with P::VC a little more, I discovered that it isn't even the case that everything it throws inherits from Exception::Class.    There are several assertion classes that can be thrown whenever params don't match the specified type. 

Even a minimal interface that just takes whatever exception is already being thrown and passes it to a callback would be a small step forward.    Having a unified k/v interface would be more ideal but could prove to be a significant undertaking.

**Comment by autarch** [comment]
The challenge here is that we have to deal with 3 type systems, each with their own exception classes.

It sounds like you just want to wrap the entire validation in a try/catch that rethrows using your own exception classes, maybe. Does that even need an API change in this module? I suppose it might make wrapping it that way more convenient.

**Comment by dwright** [comment]
Hi Dave,

I think you're exactly right.   Adding a callback for a wrapper might make things more convenient.   But in practice, not necessary at all.     

We've been using this in production for about 4 months now.  Our solution was to just abstract the whole thing away to a module that returns a build_validator() sub that calls validaton_for() with the parameters we send in, and then returns a coderef that does what we want.      It's working okay enough for us.    I'm not sure that adding callback would have added any value.

Thanks for your patience.    I guess this is a non-issue.

**Comment by autarch** [comment]
You could get some additional speed by calling `source_for` and using what it returns to compile your own sub (use `Eval::Closure`) that wraps the validation and rethrows the exception. This would save a sub call per validation, so it might be worth it.
